sonar.projectKey=2024ht66529-Abhijat_Assign2_ACEest
sonar.organization=2024ht66529-abhijat
sonar.projectName=ACEest
sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
