sonar.projectKey=aceestver
sonar.projectName=Aceestver Flask Application
sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
