apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceestver
  labels:
    app: aceestver
    version: "${APP_VERSION}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceestver
  template:
    metadata:
      labels:
        app: aceestver
    spec:
      containers:
      - name: aceestver
        # The Jenkinsfile 'sed' command targets this line specifically
        image: 2024ht66529/aceestver:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
