apiVersion: v1
kind: Service
metadata:
  name: aceestver-service
  labels:
    app: aceestver
  annotations:
    # This annotation is ignored by Minikube but used by AWS/EKS
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"   # or "classic"
spec:
  selector:
    app: aceestver
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30080   # Minikube will use this NodePort
  type: NodePort        # Default for local testing
